Repository WordPress/twentytwentyone, pull requests merged in 2020-11, with the labels that each got.

#742 Tidy up full-width group block children when the group has padding
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/05-blocks/group/_editor.scss
  assets/sass/05-blocks/group/_style.scss
  style-rtl.css
  style.css
Labels: [Type] Bug

#755 Add visible focus indicator to linked images
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/04-elements/links.scss
  assets/sass/05-blocks/gallery/_style.scss
  assets/sass/05-blocks/image/_style.scss
  assets/sass/05-blocks/legacy/_style.scss
  assets/sass/05-blocks/media-text/_style.scss
  style-rtl.css
  style.css
Labels: Accessibility (a11y)

#776 Prevent :focus styles for links from effecting buttons too.
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/02-tools/mixins.scss
  style-rtl.css
  style.css
Labels: [Type] Bug

#777 Try using "bolder" for bold text inside of blockquotes.
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/01-settings/global.scss
  assets/sass/04-elements/blockquote.scss
  assets/sass/05-blocks/quote/_editor.scss
  style-rtl.css
  style.css
Labels: [Type] Bug

#778 Fix mobile menu button placement
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/sass/06-components/navigation.scss
  style-rtl.css
  style.css
Labels: [Type] Enhancement

#673 Update search block
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/js/editor.js
  assets/js/unregister-block-style.js
  assets/sass/05-blocks/search/_editor.scss
  assets/sass/05-blocks/search/_style.scss
  functions.php
  style-rtl.css
  style.css
Labels: Help wanted

#795 Button Block: Tidy up buttons block margins in the editor
  assets/css/ie-editor.css
  assets/css/style-editor.css
  assets/sass/05-blocks/button/_editor.scss
Labels: [Component] Default blocks, [Type] Bug

#791 Improve the dark mode option message in the customizer
  classes/class-twenty-twenty-one-dark-mode.php
Labels: High priority

#800 don't enlarge images
  assets/css/ie.css
  assets/sass/06-components/entry.scss
  inc/template-functions.php
  style-rtl.css
  style.css
Labels: Needs design feedback

#827 Update the privacy policy content
  classes/class-twenty-twenty-one-dark-mode.php
Labels: [Component] Dark Mode

#826 Remove is_singular() from single.php
  single.php
Labels: [Type] Code quality

#825 Update menu callback and container to false
  footer.php
  template-parts/header/site-nav.php
Labels: [Type] Code quality

#816 Update readme.txt to include information about LocalStorage
  readme.txt
Labels: [Component] Dark Mode

#847 Actions: Intentionally set the node version on lint check
  .github/workflows/lint.yml
Labels: [Component] Tooling

#851 Fix typo in the "Two images showcase" block pattern title
  inc/block-patterns.php
Labels: [Type] Bug

#849 Dark Mode: Remove toggle code from the editor
  assets/css/style-dark-mode-rtl.css
  assets/css/style-dark-mode.css
  assets/js/dark-mode-toggler.js
  assets/js/editor-dark-mode-support.js
  assets/sass/style-dark-mode.scss
  classes/class-twenty-twenty-one-dark-mode.php
Labels: [Component] Dark Mode

#793 Update the widget area top margin on mobile
  assets/css/ie.css
  assets/sass/06-components/footer.scss
  assets/sass/06-components/widgets.scss
  style-rtl.css
  style.css
Labels: Needs design feedback

#863 Fix separator width & opacity
  assets/css/ie.css
  assets/sass/05-blocks/separator/_style.scss
  style-rtl.css
  style.css
Labels: [Type] Bug

#856 Make the solid pullquote block readable and match in the editor and front
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/05-blocks/pullquote/_editor.scss
  assets/sass/05-blocks/pullquote/_style.scss
  style-rtl.css
  style.css
Labels: Needs design feedback

#861 Decrease range input thumb size on Firefox
  assets/css/ie.css
  assets/sass/04-elements/forms.scss
  style-rtl.css
  style.css
Labels: Accessibility (a11y)

#874 Only apply column text margins to full-width columns blocks
  assets/css/ie-editor.css
  assets/css/style-editor.css
  assets/sass/05-blocks/columns/_editor.scss
Labels: [Type] Bug

#883 Remove empty paragraph in Contact Information pattern
  inc/block-patterns.php
Labels: [Component] Block patterns

#881 Display a caption for featured images if one is set.
  inc/template-tags.php
Labels: Needs design feedback

#884 Social Links Block: Fix focus on default block style
  assets/css/ie.css
  assets/sass/05-blocks/social-icons/_style.scss
  style-rtl.css
  style.css
Labels: [Component] Default blocks

#859 Try: Be more specific about first/last child spacing overrides
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/02-tools/mixins.scss
  assets/sass/05-blocks/columns/_editor.scss
  assets/sass/05-blocks/cover/_editor.scss
  assets/sass/05-blocks/group/_editor.scss
  assets/sass/05-blocks/media-text/_editor.scss
  assets/sass/05-blocks/utilities/_editor.scss
Labels: [Type] Bug, [Type] Enhancement

#892 CSS: Remove `has-background-background-color` selector
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/04-elements/links.scss
  assets/sass/05-blocks/quote/_editor.scss
  assets/sass/05-blocks/quote/_style.scss
  assets/sass/05-blocks/search/_style.scss
  assets/sass/05-blocks/separator/_editor.scss
  assets/sass/05-blocks/separator/_style.scss
  assets/sass/05-blocks/utilities/_editor.scss
  assets/sass/06-components/editor.scss
  assets/sass/07-utilities/color-palette.scss
  style-rtl.css
  style.css
Labels: [Component] CSS
