Repository WordPress/twentytwentyone, pull requests merged in 2020-09, with the labels that each got.

#102 Add mobile type sizes
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/01-settings/global.scss
  style-rtl.css
  style.css
Labels: [Component] CSS, [Type] Enhancement

#62 Composer improvements
  .github/workflows/lint.yml
  .github/workflows/phpcs.yml
  composer.json
  composer.lock
  phpcs.xml.dist
  phpstan.neon
Labels: [Type] Enhancement

#131 Update URL of php.net date format table
  footer.php
Labels: [Component] Internationalization (i18n), [Type] Code quality

#135 Adds exceptions for false-positives in PHPCS checks
  phpcs.xml.dist
Labels: [Component] Tooling

#143 Update Twenty Twenty One to Twenty Twenty-One
  CONTRIBUTING.md
  assets/sass/01-settings/file-header.scss
  composer.json
  functions.php
  inc/block-patterns.php
  inc/starter-content.php
  readme.txt
Labels: [Component] Miscellaneous, [Type] Documentation

#103 Fix search block styling
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/05-blocks/search/_editor.scss
  assets/sass/05-blocks/search/_style.scss
  style-rtl.css
  style.css
Labels: [Type] Bug

#140 Add the "Two Images Showcase" block pattern
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/images/la_mousme.jpg
  assets/images/the_berceuse_woman-rocking_a_cradle.jpg
  assets/sass/05-blocks/image/_editor.scss
  assets/sass/05-blocks/image/_style.scss
  inc/block-patterns.php
  inc/block-styles.php
  phpcs.xml.dist
  readme.txt
  style-rtl.css
  style.css
Labels: Design, [Component] Block patterns, [Type] Enhancement

#152 Update border color to dark grey
  assets/sass/01-settings/global.scss
Labels: [Component] CSS

#153 Style the Latest Posts block to match the comps
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/05-blocks/latest-posts/_editor.scss
  assets/sass/05-blocks/latest-posts/_style.scss
  inc/block-styles.php
  style-rtl.css
  style.css
Labels: [Component] Default blocks, [Type] Enhancement

#150 Add "Bordered" style and "Media & Text article title" block pattern
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/images/the_poplars_at_saint_remy.jpg
  assets/sass/05-blocks/cover/_editor.scss
  assets/sass/05-blocks/cover/_style.scss
  assets/sass/05-blocks/group/_editor.scss
  assets/sass/05-blocks/group/_style.scss
  assets/sass/05-blocks/image/_editor.scss
  assets/sass/05-blocks/image/_style.scss
  assets/sass/05-blocks/media-text/_editor.scss
  assets/sass/05-blocks/media-text/_style.scss
  inc/block-patterns.php
  inc/block-styles.php
  style-rtl.css
  style.css
Labels: [Component] Block patterns, [Type] Enhancement

#151 Force #88: Use aria-current attribute on footer homepage link when home is the current page
  footer.php
Labels: [Component] Footer

#176 Fix stylelint local script
  package.json
Labels: [Component] Tooling, [Type] Bug

#147 Add options for retina logo and display site title and tagline
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/01-settings/global.scss
  classes/class-twenty-twenty-one-customize-color-control.php
  classes/class-twenty-twenty-one-customize.php
  functions.php
  inc/customizer.php
  inc/template-functions.php
  style-rtl.css
  style.css
  template-parts/header/site-branding.php
Labels: Help wanted, Needs testing

#165 Revise link styles
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/03-generic/reset.scss
  assets/sass/04-elements/links.scss
  assets/sass/06-components/editor.scss
  assets/sass/06-components/footer.scss
  assets/sass/style-editor.scss
  assets/sass/style.scss
  style-rtl.css
  style.css
Labels: Needs testing, [Component] CSS

#173 Update single page header treatment
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/05-blocks/utilities/_editor.scss
  assets/sass/06-components/single.scss
  style-rtl.css
  style.css
  template-parts/content/content-page.php
Labels: [Component] Pages, [Type] Enhancement

#174 Add Link CTA block pattern
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/01-settings/global.scss
  assets/sass/05-blocks/utilities/_editor.scss
  assets/sass/05-blocks/utilities/_style.scss
  functions.php
  inc/block-patterns.php
  style-rtl.css
  style.css
Labels: [Component] Block patterns, [Type] Enhancement

#191 Add license info for the poplars image
  readme.txt
Labels: [Type] Bug, [Type] Documentation
