Repository WordPress/twentytwentyone, pull requests merged in 2020-10, with the labels that each got.

#142 Update forms, inputs and buttons, replaces Pr/97
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/js/customize-preview.js
  assets/sass/01-settings/global.scss
  assets/sass/02-tools/extends.scss
  assets/sass/04-elements/forms-editor.scss
  assets/sass/04-elements/forms.scss
  assets/sass/05-blocks/button/_editor.scss
  assets/sass/05-blocks/button/_style.scss
  assets/sass/05-blocks/file/_editor.scss
  assets/sass/05-blocks/file/_style.scss
  assets/sass/05-blocks/search/_editor.scss
  assets/sass/05-blocks/search/_style.scss
  assets/sass/06-components/comments.scss
  assets/sass/06-components/widgets.scss
  assets/sass/style-editor.scss
  classes/class-twenty-twenty-one-custom-colors.php
  readme.txt
  searchform.php
  style-rtl.css
  style.css
Labels: Help wanted, Needs testing

#125 Revise menu and submenu spacing
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/01-settings/global.scss
  assets/sass/06-components/header.scss
  assets/sass/06-components/navigation.scss
  style-rtl.css
  style.css
Labels: Design

#132 The scrollbar always visible for menu on small devices.
  assets/css/ie.css
  assets/sass/06-components/navigation.scss
  style-rtl.css
  style.css
Labels: [Component] CSS, [Type] Bug

#172 Update the image attachment page
  assets/css/ie.css
  assets/sass/06-components/entry.scss
  image.php
  readme.txt
  style-rtl.css
  style.css
Labels: [Component] Default views

#181 Adjust widget title size and widget area spacing
  assets/css/ie.css
  assets/sass/06-components/widgets.scss
  style-rtl.css
  style.css
Labels: [Component] Footer

#234 Add descriptions to current block patterns
  inc/block-patterns.php
Labels: Accessibility (a11y), Hacktoberfest, [Component] Block patterns

#230 Update audio focus styles
  assets/css/ie.css
  assets/sass/05-blocks/audio/_style.scss
  style-rtl.css
  style.css
Labels: [Component] Default blocks

#214 Fix typo and update URL to the coding standards
  .editorconfig
  phpcs.xml.dist
Labels: [Type] Documentation

#215 File block: Added an underline to the download link in the editor.
  assets/css/ie-editor.css
  assets/css/style-editor.css
  assets/sass/05-blocks/file/_editor.scss
Labels: [Component] Default blocks

#249 Fix fullwidth blocks
  assets/css/ie.css
  assets/sass/03-generic/breakpoints.scss
  style-rtl.css
  style.css
Labels: High priority

#244 Allow for flexible logo sizes
  assets/css/ie.css
  assets/sass/06-components/header.scss
  footer.php
  functions.php
  style-rtl.css
  style.css
Labels: [Component] Footer, [Component] Header

#250 Fix left & right block align
  assets/css/ie.css
  assets/sass/05-blocks/gallery/_style.scss
  assets/sass/05-blocks/utilities/_style.scss
  style-rtl.css
  style.css
Labels: High priority

#256 Update comments pagination
  assets/css/ie.css
  assets/sass/06-components/comments.scss
  assets/sass/06-components/pagination.scss
  comments.php
  style-rtl.css
  style.css
Labels: [Component] Blog

#229 New pullquote block design
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/01-settings/global.scss
  assets/sass/05-blocks/pullquote/_editor.scss
  assets/sass/05-blocks/pullquote/_style.scss
  style-rtl.css
  style.css
Labels: [Component] Default blocks

#279 Remove retina option for logo
  classes/class-twenty-twenty-one-customize.php
  functions.php
  inc/template-functions.php
Labels: [Component] Header

#227 FIX: fixing tables with a background-color on a dark page background
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/01-settings/global.scss
  assets/sass/05-blocks/table/_editor.scss
  assets/sass/05-blocks/table/_style.scss
  style-rtl.css
  style.css
Labels: Needs testing, [Component] Default blocks

#248 Hide author bio when no description
  template-parts/post/author-bio.php
Labels: Decision needed, [Component] Blog

#281 Fix editor custom colors bug
  classes/class-twenty-twenty-one-custom-colors.php
Labels: [Component] Default blocks, [Type] Bug

#268 Hide the site title in the footer when the display option is unchecked
  footer.php
Labels: [Component] Footer

#265 Tools: Try a workflow for building CSS
  .github/workflows/build.yml
  style.css.map
Labels: [Component] Tooling

#267 Add a screen reader text with the site title to the front page
  template-parts/header/site-branding.php
Labels: [Component] Header

#300 Add custom gradients
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/07-utilities/color-palette.scss
  functions.php
  style-rtl.css
  style.css
Labels: Design, [Type] Enhancement

#262 Updated search widget and block design. Issue: #225
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/05-blocks/search/_editor.scss
  assets/sass/05-blocks/search/_style.scss
  assets/sass/06-components/widgets.scss
  style-rtl.css
  style.css
Labels: [Component] Default blocks, [Component] Footer, [Type] Task

#192 Add the large text block pattern
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/01-settings/global.scss
  assets/sass/05-blocks/blocks-editor.scss
  assets/sass/05-blocks/columns/_editor.scss
  assets/sass/05-blocks/utilities/_style.scss
  functions.php
  inc/block-patterns.php
  style-rtl.css
  style.css
Labels: Decision needed, [Component] Block patterns

#235 Update-Design: Archive Widget, Post Widget, Page Widget, Category Widget and Recent Comments Widget
  assets/css/ie.css
  assets/sass/06-components/widgets.scss
  style-rtl.css
  style.css
Labels: Decision needed, [Component] CSS, [Component] Default blocks, [Component] Footer

#269 ESLint configuration & fixes
  .eslintignore
  .eslintrc
  assets/js/customize-preview.js
  assets/js/palette-colorpicker.js
  assets/js/polyfills.js
  assets/js/primary-navigation.js
  assets/js/skip-link-focus-fix.js
  package-lock.json
  package.json
Labels: [Component] Tooling

#286 Primary Menu: Fix alignment and scrolling on mobile
  assets/css/ie.css
  assets/sass/03-generic/vertical-margins.scss
  assets/sass/06-components/header.scss
  assets/sass/06-components/navigation.scss
  style-rtl.css
  style.css
Labels: [Component] Header

#208 👌 IMPROVE: Update styles for the RSS block (#200)
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/05-blocks/blocks-editor.scss
  assets/sass/05-blocks/blocks.scss
  assets/sass/05-blocks/list/_editor.scss
  assets/sass/05-blocks/rss/_editor.scss
  assets/sass/05-blocks/rss/_style.scss
  style-rtl.css
  style.css
Labels: Decision needed, [Component] Default blocks

#283 Pagination: Wrap pagination links on smaller screens
  assets/css/ie.css
  assets/sass/06-components/pagination.scss
  inc/template-tags.php
  style-rtl.css
  style.css
Labels: [Component] Miscellaneous

#264 Fix text color on light backgrounds #261
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/07-utilities/color-palette.scss
  style-rtl.css
  style.css
Labels: [Component] Default blocks

#366 Clean up the block patterns & block styles files
  inc/block-patterns.php
  inc/block-styles.php
Labels: [Type] Code quality

#337 Columns Block: Try adding a "negative margins" block style
  assets/css/ie-editor.css
  assets/css/ie-editor.css.map
  assets/css/ie.css
  assets/css/ie.css.map
  assets/css/style-editor.css
  assets/css/style-editor.css.map
  assets/sass/05-blocks/columns/_editor.scss
  assets/sass/05-blocks/columns/_style.scss
  inc/block-styles.php
  style-rtl.css
  style.css
  style.css.map
Labels: Design, [Component] Block patterns, [Component] Default blocks

#372 Add flex-grow rule to overlapping columns block style.
  assets/css/ie.css
  assets/css/ie.css.map
  assets/sass/05-blocks/columns/_style.scss
  style-rtl.css
  style.css
  style.css.map
Labels: [Type] Bug

#371 Fix alignement issue on alignleft pullquote. Fixes #359.
  assets/css/ie.css
  assets/css/ie.css.map
  assets/sass/05-blocks/pullquote/_style.scss
  style-rtl.css
  style.css
  style.css.map
Labels: [Component] CSS, [Component] Default blocks

#299 Try: Adding "Portfolio List" block pattern + modifying "wide" separator style
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/01-settings/global.scss
  assets/sass/05-blocks/separator/_editor.scss
  assets/sass/05-blocks/separator/_style.scss
  inc/block-patterns.php
  style-rtl.css
  style.css
Labels: [Component] Block patterns

#370 Add overlapping images block pattern
  inc/block-patterns.php
Labels: [Component] Block patterns

#393 Add "Overlapping Images and Text" block pattern
  assets/images/roses_a.jpg
  assets/images/roses_b.jpg
  inc/block-patterns.php
  readme.txt
Labels: [Component] Block patterns, [Type] Enhancement

#421 Fix font size for portfolio list pattern.
  inc/block-patterns.php
Labels: [Type] Bug

#420 Add a z-index value to the overlapping columns block style
  assets/css/ie-editor.css
  assets/css/ie-editor.css.map
  assets/css/ie.css
  assets/css/ie.css.map
  assets/css/style-editor.css
  assets/css/style-editor.css.map
  assets/sass/05-blocks/columns/_editor.scss
  assets/sass/05-blocks/columns/_style.scss
  style-rtl.css
  style.css
  style.css.map
Labels: [Type] Bug

#413 Fix site-logo and footer text alignment
  assets/css/ie.css
  assets/css/ie.css.map
  assets/sass/06-components/footer.scss
  style-rtl.css
  style.css
  style.css.map
Labels: Needs design feedback

#434 Use dotted separator in Media & Text Article Title pattern
  inc/block-patterns.php
Labels: [Type] Enhancement

#428 Update large text block pattern to use a wide-width header
  inc/block-patterns.php
Labels: [Type] Enhancement

#433 Update "read more" text to "Continue reading"
  inc/template-functions.php
  template-parts/content/content-single.php
  template-parts/content/content.php
Labels: [Component] Blog

#432 Fix "Edit [Post Name]" links in NVDA
  inc/template-tags.php
Labels: Accessibility (a11y)

#435 Header: Center logo above header if all 3 items are visible
  assets/css/ie.css
  assets/css/ie.css.map
  assets/sass/06-components/header.scss
  style-rtl.css
  style.css
  style.css.map
  template-parts/header/site-branding.php
Labels: [Component] Header

#391 Post Formats
  archive.php
  assets/css/ie.css
  assets/css/ie.css.map
  assets/sass/06-components/archives.scss
  functions.php
  inc/template-functions.php
  index.php
  search.php
  style-rtl.css
  style.css
  style.css.map
  template-parts/content/content-excerpt.php
  template-parts/excerpt/excerpt-aside.php
  template-parts/excerpt/excerpt-audio.php
  template-parts/excerpt/excerpt-chat.php
  template-parts/excerpt/excerpt-gallery.php
  template-parts/excerpt/excerpt-image.php
  template-parts/excerpt/excerpt-link.php
  template-parts/excerpt/excerpt-quote.php
  template-parts/excerpt/excerpt-status.php
  template-parts/excerpt/excerpt-video.php
  template-parts/excerpt/excerpt.php
  template-parts/header/excerpt-header.php
Labels: Needs testing

#427 Fix default text colors within the Cover Block
  assets/css/ie-editor.css
  assets/css/ie-editor.css.map
  assets/css/ie.css
  assets/css/ie.css.map
  assets/css/style-editor.css
  assets/css/style-editor.css.map
  assets/sass/05-blocks/cover/_editor.scss
  assets/sass/05-blocks/cover/_style.scss
  style-rtl.css
  style.css
  style.css.map
Labels: [Component] Default blocks

#388 Add footer navigation
  assets/css/ie.css
  assets/sass/06-components/footer-navigation.scss
  assets/sass/06-components/footer.scss
  assets/sass/style.scss
  classes/class-twenty-twenty-one-svg-icons.php
  comments.php
  footer.php
  functions.php
  header.php
  inc/menu-functions.php
  inc/template-functions.php
  inc/template-tags.php
  single.php
  style-rtl.css
  style.css
Labels: Needs design feedback

#423 Fix up separator styles
  assets/css/ie-editor.css
  assets/css/ie-editor.css.map
  assets/css/ie.css
  assets/css/ie.css.map
  assets/css/style-editor.css
  assets/css/style-editor.css.map
  assets/sass/01-settings/global.scss
  assets/sass/05-blocks/separator/_editor.scss
  assets/sass/05-blocks/separator/_style.scss
  package-lock.json
  style-rtl.css
  style.css
  style.css.map
Labels: [Component] Default blocks

#476 Unregister "Wide" separator style, replace with new "Thick" style
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/css/style-editor.css.map
  assets/js/unregister-block-style.js
  assets/sass/05-blocks/separator/_editor.scss
  assets/sass/05-blocks/separator/_style.scss
  functions.php
  inc/block-patterns.php
  inc/block-styles.php
  style-rtl.css
  style.css
Labels: [Component] Default blocks, [Type] Enhancement

#452 The password input field is the wrong size
  assets/sass/05-blocks/blocks.scss
  assets/sass/05-blocks/password/_style.scss
  inc/template-functions.php
Labels: Needs design feedback

#502 Adjust text-underline-offset for post titles
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/sass/06-components/entry.scss
  style-rtl.css
  style.css
Labels: [Type] Enhancement

#504 Remove space in post navigation and re-align the arrows.
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/sass/06-components/pagination.scss
  single.php
  style-rtl.css
  style.css
Labels: [Type] Bug

#442 Mobile Header Layouts
  assets/css/ie.css
  assets/sass/06-components/header.scss
  assets/sass/06-components/navigation.scss
  header.php
  style-rtl.css
  style.css
  template-parts/header/site-header.php
Labels: Needs design feedback, [Component] Header

#512 Code cleanup: Remove unused functions, classes, extraneous comments
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/sass/05-blocks/utilities/_style.scss
  assets/sass/06-components/footer.scss
  comments.php
  footer.php
  functions.php
  image.php
  inc/template-tags.php
  style-rtl.css
  style.css
Labels: [Type] Code quality

#514 Image Attachment: Fix meta spacing on small screen
  assets/css/ie.css
  assets/sass/06-components/entry.scss
  style-rtl.css
  style.css
Labels: Low priority

#524 Add page before numbered pagination
  comments.php
  inc/template-tags.php
Labels: Accessibility (a11y), Needs design feedback

#556 Update default form label weight
  assets/css/style-editor.css
  assets/sass/01-settings/global.scss
  assets/sass/05-blocks/search/_editor.scss
  assets/sass/05-blocks/search/_style.scss
  assets/sass/06-components/comments.scss
  assets/sass/06-components/widgets.scss
  style-rtl.css
  style.css
Labels: [Component] CSS, [Component] Forms

#561 Reduce size of comment meta
  assets/sass/06-components/comments.scss
  style-rtl.css
  style.css
Labels: [Component] Blog

#559 Buttons: Fix search button style
  assets/css/ie.css
  assets/sass/05-blocks/button/_style.scss
  style-rtl.css
  style.css
Labels: [Component] CSS, [Type] Bug

#513 Try adding blockquote styles
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/01-settings/global.scss
  assets/sass/04-elements/misc.scss
  assets/sass/05-blocks/quote/_editor.scss
  assets/sass/05-blocks/quote/_style.scss
  style-rtl.css
  style.css
Labels: [Type] Enhancement

#456 Post Formats: Fix embeds in audio & video formats
  inc/template-functions.php
  template-parts/excerpt/excerpt-aside.php
  template-parts/excerpt/excerpt-audio.php
  template-parts/excerpt/excerpt-chat.php
  template-parts/excerpt/excerpt-gallery.php
  template-parts/excerpt/excerpt-image.php
  template-parts/excerpt/excerpt-link.php
  template-parts/excerpt/excerpt-quote.php
  template-parts/excerpt/excerpt-status.php
  template-parts/excerpt/excerpt-video.php
Labels: [Component] Post formats

#595 Clean up custom properties: Remove unused, update use where appropriate
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/01-settings/global.scss
  assets/sass/04-elements/blockquote.scss
  assets/sass/05-blocks/cover/_editor.scss
  assets/sass/05-blocks/cover/_style.scss
  assets/sass/06-components/entry.scss
  assets/sass/06-components/header.scss
  assets/sass/06-components/navigation.scss
  assets/sass/06-components/pagination.scss
  style-rtl.css
  style.css
Labels: [Component] CSS

#598 Pagination: Add page number placeholder to translated string
  image.php
  template-parts/content/content-page.php
  template-parts/content/content-single.php
  template-parts/content/content.php
Labels: [Component] Internationalization (i18n)

#317 Firefox: Indicate focus on the scrollable area of the responsive menu
  assets/css/ie.css
  assets/sass/06-components/navigation.scss
  style-rtl.css
  style.css
Labels: Accessibility (a11y), Help wanted, [Type] Question

#615 Colors: Add an option to disable the "dark mode" functionality (continuation of #599)
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/js/customize-helpers.js
  assets/js/customize.js
  assets/sass/01-settings/global.scss
  classes/class-twenty-twenty-one-custom-colors.php
  classes/class-twenty-twenty-one-customize.php
  functions.php
  style-rtl.css
  style.css
Labels: Accessibility (a11y), High priority, Needs design feedback

#610 Add vertical margin to full width blocks without background
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/sass/03-generic/vertical-margins.scss
  style-rtl.css
  style.css
Labels: Needs design feedback

#584 Improve styling of the <fieldset> element
  assets/css/ie.css
  assets/sass/04-elements/forms.scss
  style-rtl.css
  style.css
Labels: Needs design feedback

#645 Match search block style in editor and frontend
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/05-blocks/search/_editor.scss
  assets/sass/05-blocks/search/_style.scss
  style-rtl.css
  style.css
Labels: Needs design feedback

#653 Fix custom column width appearance combined with the Overlap columns block style
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/sass/05-blocks/columns/_style.scss
  style-rtl.css
  style.css
Labels: [Type] Bug

#677 Button styles: refactor extend to mixin
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/02-tools/extends.scss
  assets/sass/02-tools/mixins.scss
  assets/sass/05-blocks/button/_editor.scss
  assets/sass/05-blocks/button/_style.scss
  assets/sass/05-blocks/file/_editor.scss
  assets/sass/05-blocks/file/_style.scss
  assets/sass/05-blocks/search/_editor.scss
  assets/sass/style-editor.scss
  assets/sass/style.scss
  style-rtl.css
  style.css
Labels: [Type] Code quality

#625 Update the background color of input fields
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/01-settings/global.scss
  assets/sass/04-elements/forms.scss
  style-rtl.css
  style.css
Labels: Accessibility (a11y), Decision needed, Help wanted, Needs design feedback, Needs testing

#701 Increase button focus offset
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/02-tools/extends.scss
  style-rtl.css
  style.css
Labels: [Component] CSS, [Component] Forms

#697 Add missing archive descriptions
  archive.php
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/sass/06-components/archives.scss
  style-rtl.css
  style.css
Labels: Needs design feedback

#700 Verse Block: Inherit the parent text color
  assets/css/ie-editor.css
  assets/css/style-editor.css
  assets/sass/05-blocks/verse/_editor.scss
Labels: Gutenberg

#695 Style submenus container
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/01-settings/global.scss
  assets/sass/05-blocks/navigation/_style.scss
  assets/sass/06-components/navigation.scss
  style-rtl.css
  style.css
Labels: Needs design feedback

#676 Update link focus background color
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/04-elements/links.scss
  classes/class-twenty-twenty-one-custom-colors.php
  style-rtl.css
  style.css
Labels: Accessibility (a11y), Needs design feedback

#730 Customizer: Add `has-background-white` class to the customizer preview
  assets/js/customize-preview.js
Labels: [Type] Bug

#732 Cover Block: Fix default overlay color
  assets/css/ie.css
  assets/sass/05-blocks/cover/_style.scss
  style-rtl.css
  style.css
Labels: [Component] Default blocks

#743 Remove left padding from latest comments block.
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/05-blocks/blocks-editor.scss
  assets/sass/05-blocks/latest-comments/_editor.scss
  assets/sass/05-blocks/latest-comments/_style.scss
  style-rtl.css
  style.css
Labels: [Type] Enhancement

#731 Fix margins on Media & Text with vertical alignment
  assets/css/ie-editor.css
  assets/css/style-editor.css
  assets/sass/05-blocks/media-text/_editor.scss
Labels: [Component] Default blocks

#725 Portfolio List block pattern: fix image dimensions
  inc/block-patterns.php
Labels: [Component] Block patterns, [Type] Enhancement

#687 Adds word break to latest posts grid view
  assets/css/ie-editor.css
  assets/css/ie.css
  assets/css/style-editor.css
  assets/sass/05-blocks/latest-posts/_editor.scss
  assets/sass/05-blocks/latest-posts/_style.scss
  style-rtl.css
  style.css
Labels: Help wanted, Needs testing
